# Generated by Django 3.0.8 on 2020-07-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('sector', models.IntegerField(choices=[(1, 'Financials'), (2, 'Utilities'), (3, 'Consumer Discretionary'), (4, 'Consumer Staples'), (5, 'Energy'), (6, 'Health Care'), (7, 'Industrials'), (8, 'Technology'), (9, 'Telecommunications'), (10, 'Matirials'), (11, 'REIT')])),
                ('address', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('short_name', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('open', models.DecimalField(decimal_places=4, max_digits=15)),
                ('high', models.DecimalField(decimal_places=4, max_digits=15)),
                ('low', models.DecimalField(decimal_places=4, max_digits=15)),
                ('close', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.PositiveIntegerField()),
                ('date', models.DateField(unique_for_date=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='dailyprice',
            index=models.Index(fields=['symbol', 'date'], name='app_dailypr_symbol_2173b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyprice',
            unique_together={('symbol', 'date')},
        ),
    ]
